### ISSUE TITLE
Implement iThemes Security to Sonaria

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#6]
Not sure where our licensing stands.

Just tried to log in with the credentials from the installation of the corp site and the info didn't work.

I believe it was purchased by Nik and probably used the registration@ email address...which I don't have access to.

Stay tuned.

**Comment by TheMarketingGuy** [comment]
Ok...got access. Our subscription is for "Unlimited Sites".

QUESTION IS: Do you feel we need this added layer or would it be redundant?

**Comment by nikdagostino** [comment]
In my opinion since we really only used their security plugin and backup buddy plugin is seems like at a minimum the backup buddy plugin is definitely redundant since that’s built natively into WP-Engine. Depending on what WP-Engine has to offer as far as security but the iThemes security plugin was pretty good if I recall correctly.

Jeff – Do you know if Sonaria is built on the WordPress platform?

Best regards,
Nik D’Agostino

**Comment by TheMarketingGuy** [comment]
@nikdagostino - Yes. Sonaria is currently on a basic WordPress core.

**Comment by BigActual** [comment]
We're fine with the ithemes plugin in place on Sonaria. There are features being used that are not redundant.

**Comment by TheMarketingGuy** [comment]
@BigActual - so you will be installing the iThemes security plugin?

**Comment by BigActual** [comment]
Yes.

**Comment by TheMarketingGuy** [comment]
GREAT!

**Comment by TheMarketingGuy** [comment]
Status? I need to go LIVE on by Monday.

Ok...live by Wednesday morning 8:00 AM.

**Comment by d4mation** [comment]
If you have a valid license for this additional site, I could just upload the version of it that is up on lowrysolutions.com currently and the License Key could be added via their interface then.

**Comment by TheMarketingGuy** [comment]
Our subscription is for "unlimited" sites.
I can toss you over the key.

**Comment by d4mation** [comment]
Implemented
