### ISSUE TITLE
Sonaria Site content additions/updates

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#9]
1. Update to white type color, add in "Know More • Do More"
2. Add phone number 877-256-9962 (please make it clickable with the appropriate tel: html code)
3. Can the "Sonaria" page name NOT be displayed?

![image](https://user-images.githubusercontent.com/24927952/37727140-75684d06-2d0d-11e8-8f91-36277dd367a3.png)

**Comment by d4mation** [comment]
@TheMarketingGuy 

I've made the changes above. You can control the Phone Number by going to Appearance -> Customizer -> Sonaria Settings

However, I did not add the "Know More &bull; Do More" text. I'm wondering if that should instead be moved from the Site Tagline into the Site Title?

The "Sonaria" text there now is the Site Title, so that would be a quick way to get it there. And it wouldn't end up looking any different in Search Results since the Tagline is included there anyhow. The main difference would be that the "Know More &bull; Do More" text would be included in the `<title>` tag for all Interior Pages, whereas how it is now it would only show on the Home Page.

![image](https://user-images.githubusercontent.com/7770631/37771709-cc922736-2dae-11e8-86be-bd1b87ba5745.png)

**Comment by TheMarketingGuy** [comment]
think you are set on this one. Good to close.
